package org.usta.formularios;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

import org.usta.DAOS.ConciertoDAO;
import org.usta.DAOS.TipoConciertoDao;
import org.usta.modelos.Concierto;
import org.usta.modelos.TipoConcierto;

public class FrmConciertoCrear extends javax.swing.JInternalFrame {

    private Map<Integer, Integer> codigosTipoConcierto = new HashMap<>();
    private Map<Integer, Integer> codigosArtista = new HashMap<>();

    private DefaultComboBoxModel modeloComboTC = new DefaultComboBoxModel();
    private DefaultComboBoxModel modeloArtistas = new DefaultComboBoxModel();

    public FrmConciertoCrear() {
        initComponents();
        comboTipoC.setModel(modeloComboTC);

        cargarTipoC();//llama al combo los datos
    }

    private void cargarTipoC() {

        Integer indice = 0;

        codigosTipoConcierto.put(indice, indice);

        List<TipoConcierto> arregloTC;

        TipoConciertoDao objDaoTC = new TipoConciertoDao();
        arregloTC = objDaoTC.consultar("");

        modeloComboTC.addElement("Seleccione una Opción"); //Esto es para que no muestre el primer dato

        for (TipoConcierto objTC : arregloTC) {

            indice++;

            modeloComboTC.addElement(objTC.getNombreTipoConcierto()); //addElement añade cosas al combo y solamente le pone el nombre 

            codigosTipoConcierto.put(indice, objTC.getCodTipoConcierto());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearConcierto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaNombreConcierto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboTipoC = new javax.swing.JComboBox<>();
        fConcierto = new com.toedter.calendar.JDateChooser();
        panelCabeza = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelPies = new javax.swing.JPanel();
        btnCrearC = new javax.swing.JButton();

        panelCrearConcierto.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del concierto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha del Concierto");

        cajaNombreConcierto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de concierto");

        comboTipoC.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        comboTipoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " " }));
        comboTipoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCActionPerformed(evt);
            }
        });

        fConcierto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCrearConciertoLayout = new javax.swing.GroupLayout(panelCrearConcierto);
        panelCrearConcierto.setLayout(panelCrearConciertoLayout);
        panelCrearConciertoLayout.setHorizontalGroup(
            panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearConciertoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaNombreConcierto)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(panelCrearConciertoLayout.createSequentialGroup()
                .addGroup(panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearConciertoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(comboTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCrearConciertoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCrearConciertoLayout.setVerticalGroup(
            panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearConciertoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaNombreConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(comboTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        panelCabeza.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creacion de conciertos");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCabezaLayout = new javax.swing.GroupLayout(panelCabeza);
        panelCabeza.setLayout(panelCabezaLayout);
        panelCabezaLayout.setHorizontalGroup(
            panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabezaLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        panelCabezaLayout.setVerticalGroup(
            panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabezaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelPies.setBackground(new java.awt.Color(51, 0, 51));

        btnCrearC.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnCrearC.setText("Crear");
        btnCrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPiesLayout = new javax.swing.GroupLayout(panelPies);
        panelPies.setLayout(panelPiesLayout);
        panelPiesLayout.setHorizontalGroup(
            panelPiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPiesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearC)
                .addGap(231, 231, 231))
        );
        panelPiesLayout.setVerticalGroup(
            panelPiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPiesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCrearC)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearConcierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCabeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelPies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCrearConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCActionPerformed

        try {
            Integer indiceCodTipoConciertoSeleccionado, codTipoConciertoFinal;
            String cadenaNombre, cadenaFecha;
            String formatoCalendario = "EEE MMM dd HH:mm:ss zzz yyyy";
 
            Date fechaCalendario;

            indiceCodTipoConciertoSeleccionado = comboTipoC.getSelectedIndex();

            codTipoConciertoFinal = codigosTipoConcierto.get(indiceCodTipoConciertoSeleccionado);

            cadenaNombre = cajaNombreConcierto.getText();
            cadenaFecha = fConcierto.getDate().toString();

            SimpleDateFormat formatoAntiguo = new SimpleDateFormat(formatoCalendario, Locale.ENGLISH);
            fechaCalendario = formatoAntiguo.parse(cadenaFecha);

            // System.out.println("Formato antiguo: "+ formatoAntiguo);
            //System.out.println("FechaCalendario: "+ fechaCalendario);
            TipoConcierto miTipo = new TipoConcierto(codTipoConciertoFinal, "");
            
            Concierto objConcierto = new Concierto(0, cadenaNombre, fechaCalendario, miTipo);
            ConciertoDAO objConciertoDao  =  new ConciertoDAO();
            
            if (objConciertoDao.agregar(objConcierto)) {
                
                System.out.println("Registro Exitoso");
                
            }

        } catch (ParseException ex) {
            Logger.getLogger(FrmConciertoCrear.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCrearCActionPerformed

    private void comboTipoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearC;
    private javax.swing.JTextField cajaNombreConcierto;
    private javax.swing.JComboBox<String> comboTipoC;
    private com.toedter.calendar.JDateChooser fConcierto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelCabeza;
    private javax.swing.JPanel panelCrearConcierto;
    private javax.swing.JPanel panelPies;
    // End of variables declaration//GEN-END:variables
}
